# Generated by Django 5.1.1 on 2024-09-08 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_category_super_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_categories",
                to="products.category",
                verbose_name="category",
            ),
        ),
    ]
