# Generated by Django 5.1.1 on 2024-09-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_category_product_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="subtitle",
        ),
    ]
