# Generated by Django 5.1.1 on 2024-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_invoice_invoiceitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("discount", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Price reduction action",
                "verbose_name_plural": "Price reduction actions",
                "db_table": "products_price_action",
            },
        ),
    ]
