# Generated by Django 5.1.1 on 2024-09-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_paid_at_alter_order_moderation_status_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                    ("cancelled_by_manager", "Cancelled by manager"),
                    ("cancelled_by_client", "Cancelled by client"),
                ],
                db_index=True,
                default="new",
                max_length=30,
                verbose_name="moderation status",
            ),
        ),
    ]
